### ISSUE TITLE
Refuse to run tested setup if already existing

### ISSUE THREAD

**Issue by fulldecent** [EYBlockchain/nightfall#79] opened 2019-07-21 08:28 UTC
The trusted setup process takes an hour or so to run and each time you run it you get different results.

Currently, the trusted setup process will permanently overwrite any previous outputs. There are workarounds for this including documentation and the safe-dump folder.

This is unnecessary complexity. Instead, the trusted setup should simply refuse to run if files already exist in the output directory. It should be the responsibility of the end user to delete any files if that is their intent.

**Comment by ocgordon** [comment] 2019-08-02 14:54
@fulldecent Can you elaborate on what you mean by different results?

**Comment by fulldecent** [comment] 2019-08-02 19:32
The generated keys include entropy.

**Comment by ChaitanyaKonda** [comment] 2019-10-23 09:34
#189 is a duplicate of this. Closing this because the other issue explains in detail.

**Closed by ChaitanyaKonda** 2019-10-23 09:34 UTC
Labels: low priority
